apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-data
subjects:
- kind: ServiceAccount
  name: pods-data
  namespace: pods-data
roleRef:
  kind: ClusterRole
  name: pods-data
  apiGroup: rbac.authorization.k8s.io