apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pods-data
  name: pods-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pods-data
  template:
    metadata:
      labels:
        app: pods-data
    spec:
      containers:
      - image: yarozen/pods-data:21
        name: pods-data
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      serviceAccountName: pods-data