apiVersion: v1
kind: Service
metadata:
  labels:
    app: pods-data
  name: pods-data
  namespace: pods-data
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: pods-data